// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsantprpdytoyzmearrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYW50cHJwZHl0b3l6bWVhcnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTMwNTksImV4cCI6MjA1ODkyOTA1OX0.8jaATItoe5dAMC-yr4AmRM3Jzgmj_v7uYZw-JZMmnxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});